### PR TITLE
Replaced ss14 icons with weaselstation icons

### PR DESCRIPTION
**Pull request by Teapug**
# Replaced the SS14 icons with shitty weasel station icons:
icon-256x256

too lazy to do the logo tho

### CODE REVIEW

**Comment by Kirikii** [comment]
looks good but the anti aliasing is really bad and I think the colours should be flipped

**Comment by GroggleG** [comment]
I do appreciate the help, but I already have the font and the way you put it together is wonky. Thanks for reminding me where to put the icons though! (And for your contribution :godo:)

**Comment by GroggleG** [comment]
fuck it, works for now.

**Review by GroggleG — APPROVED** [review]
works

**Pull request merged**
