### PR TITLE
Pact Major Update

### PR DESCRIPTION
**Pull request by LukeZurg22**
Door above AME starts now powered.
No ““large”” quantity of plasma and uranium windows, but some uranium windows near cargo changed to a tasteful clockwork variant.
Made Science less cramped.
RD server was given a windoor for access. Kept in box for safety.
Moved Science APC to be inside of science.
Made Cargo less palettes and more filled-in.
Added temperature control to Cook’s Freezer.
Added Kitchen Shelf to kitchen.
Fixed clown horn being embedded in wall.
Atmospherics redone w. New chambers. Atmos Tech still has setup to do.
Named most APCs.
Security overhauled to be much nicer.
Atmos pipelines colored.

### CODE REVIEW

**Comment by LukeZurg22** [comment]
The map works fine. This might have a merge conflict with the existing Pact map because of course it will. I don't care, and I'm too tired to go through some process to make the faulty as hell automatic tracker be happy.

**Comment by hereelabs** [comment]
TEG was added as well. This is a secret we are hiding from you on purpose.

**Comment by Kirikii** [comment]
the maps are supposed be located in /Maps/_Weaselstation

**Comment by LukeZurg22** [comment]
I don't know what to tell ya. I made a fresh pull of Weasel just in case and put the Pact map.yml where its always been.

**Comment by Kirikii** [comment]
it was changed (for some reason) before the new repo was opened. its _Weaselstation now

**Comment by GroggleG** [comment]
Same thing that happened before, why is Pact continuing to cause merge conflicts? Ill try to figure this out when I have time.

**Comment by GroggleG** [comment]
Do you plan to continue work on Pact? Otherwise with your permission I may fix bugs and change it to be a "variant" of what it was.

**Comment by LukeZurg22** [comment]
> Do you plan to continue work on Pact? Otherwise with your permission I may fix bugs and change it to be a "variant" of what it was.

I plan to continue working on pact elsewhere. I'd like credit as I spent sleepless nights on it, though under MIT, it's optional. Do as you please.

**Comment by GroggleG** [comment]
Ill credit you as the creator, and the map as modified simply out of respect for the labour. Au revoir.

**Comment by GroggleG** [comment]
Closing for now, I have bigger fish to fry and not enough time to to this.

**Pull request closed without merging**
